import { ImportManager } from './core/ImportManager.js'
import { LoadingScreen } from './ui/LoadingScreen.js'

let loadingScreen = new LoadingScreen(document.getElementById('loading-screen'), document.getElementById('loading-text'), document.getElementById('loading-bar'))
let importMap = new Map()
importMap.set('THREE', 'three')
importMap.set('GLTF','gltf-loader')
importMap.set('MATHS', '../helpers/maths.js')
importMap.set('HOTSPOT', '../core/HotSpot.js')
importMap.set('SCENE','../core/SceneManager.js')
importMap.set('MISC','../helpers/misc.js')
importMap.set('ACTOR','../core/Actor.js')
importMap.set('CAMERA','../camera_managers/OrbitalCameraManager.js')
importMap.set('LIGHT','../core/Light.js')
importMap.set('INPUT','../core/InputManager.js')
importMap.set('AR','../ui/ARViewer.js')
importMap.set('COLOR','../ui/ColorMenu.js')
importMap.set('NAVBAR','../ui/NavigationBar.js')
importMap.set('SLIDER','../ui/Slider.js')
importMap.set('VIDEO','../ui/VideoPlayer.js')
importMap.set('LOADER','../core/AssetLoader.js')

ImportManager.execute(importMap, (name, module, progress) => 
{
    loadingScreen.update(Math.round((progress * 33)/100))
    importMap.set(name, module)
}, onImport)

function onImport()
{
    let GLTF = importMap.get('GLTF')
    let THREE = importMap.get('THREE')
    let LOADER = importMap.get('LOADER')
    let loader = new LOADER.AssetLoader()
    loader.addTextureLoader('../assets/envmap.png', new THREE.TextureLoader())
    loader.addGLTFLoader('../assets/scene.glb', new GLTF.GLTFLoader())
    loader.addGLTFLoader('../assets/eq_animation.glb', new GLTF.GLTFLoader())
    loader.execute((p)=>loadingScreen.update(Math.round((p * 67)/100) + 33), onLoadComplete)
}

function onLoadComplete(assetMap)
{
    let colors = ['#FFFFFF', '#555555', '#786D5F', '#D4C59C', '#CD7F32']
    let COLOR = importMap.get('COLOR')
    let colorMenu = new COLOR.ColorMenu(document.getElementById('color-menu-container'), colors)
    let SLIDER = importMap.get('SLIDER')
    let slider =  new SLIDER.Slider(document.getElementById('slider-container'), document.getElementById('slider'))
    let NAVBAR = importMap.get('NAVBAR')
    let navBarManager = new NAVBAR.NavigationBarManager()
    let navBarLightItem = new NAVBAR.NavigationBarItem(document.getElementById('nav-bar-light'), document.getElementById('nav-light-img'))
    navBarLightItem.setCustomValue('sliderValue', 0)
    navBarLightItem.setOnSelect((navBarLightItem)=>{
        slider.show(true)
        slider.setValue(navBarLightItem.getCustomValue('sliderValue'))
        slider.setType('slider-light')
        navBarLightItem.setImage('./assets/light-icon-gray.png')
        navBarLightItem.setContainerClass('nav-bar-item-outer-selected')
    })
    navBarLightItem.setOnUnselect(()=>{
        slider.show(false)
        navBarLightItem.setImage('./assets/light-icon-orange.png')
        navBarLightItem.setContainerClass('nav-bar-item-outer')
    })
    navBarManager.addItem(navBarLightItem)
    let navBarRoofItem = new NAVBAR.NavigationBarItem(document.getElementById('nav-bar-roof'), document.getElementById('nav-roof-img'))
    navBarRoofItem.setCustomValue('sliderValue', 0)
    navBarRoofItem.setOnSelect((navBarRoofItem)=>{
        slider.show(true)
        slider.setValue(navBarRoofItem.getCustomValue('sliderValue'))
        slider.setType('slider-roof')
        navBarRoofItem.setImage('./assets/roof-icon-gray.png')
        navBarRoofItem.setContainerClass('nav-bar-item-outer-selected')
    })
    navBarRoofItem.setOnUnselect(()=>{
        slider.show(false)
        navBarRoofItem.setImage('./assets/roof-icon-orange.png')
        navBarRoofItem.setContainerClass('nav-bar-item-outer')
    })
    navBarManager.addItem(navBarRoofItem)
    let navBarColorItem = new NAVBAR.NavigationBarItem(document.getElementById('nav-bar-color'), document.getElementById('nav-color-img'))
    navBarColorItem.setOnSelect((navBarColorItem)=>{
        colorMenu.show(true)
        navBarColorItem.setImage('./assets/color-icon-gray.png')
        navBarColorItem.setContainerClass('nav-bar-item-outer-selected')
    })
    navBarColorItem.setOnUnselect(()=>{
        colorMenu.show(false)
        navBarColorItem.setImage('./assets/color-icon-orange.png')
        navBarColorItem.setContainerClass('nav-bar-item-outer')
    })
    navBarManager.addItem(navBarColorItem)
    let AR = importMap.get('AR')
    let arViewer = new AR.ARViewer(document.getElementById('ar-button'))
    let MISC = importMap.get('MISC')
    arViewer.show(MISC.MISC.isHandHeldDevice())
    document.body.onresize = ()=>{
        if (!loadingScreen.isVisible())
            arViewer.show(importMap.get('MISC').MISC.isHandHeldDevice())
    }
    let THREE = importMap.get('THREE')
    const canvas = document.querySelector('canvas')
    const lookAtPosition = new THREE.Vector3(0, 0, -5)
    let SCENE = importMap.get('SCENE')
    let sceneManager = new SCENE.SceneManager(canvas)
    let CAMERA = importMap.get('CAMERA')
    let cameraManager = new CAMERA.OrbitalCameraManager('Camera', 90, lookAtPosition)
    sceneManager.register(cameraManager)
    sceneManager.setActiveCamera('Camera')
    let LIGHT = importMap.get('LIGHT')
    let directLight = new LIGHT.DirectLight('DirectLight', new THREE.Vector3(0, 150, 100), 5, lookAtPosition)
    sceneManager.register(directLight)
    sceneManager.register(new LIGHT.AmbientLight('AmbientLight', 0xffffff, 0.8))
    let INPUT = importMap.get('INPUT')
    sceneManager.register(new INPUT.InputManager('Input', canvas))
    let ACTOR = importMap.get('ACTOR')
    let background = new ACTOR.ShapeActor('Background', new THREE.SphereGeometry(100, 256, 16),  new THREE.MeshBasicMaterial( { color: 0xffffff,  map: assetMap.get('../assets/envmap.png'), side: THREE.BackSide }))
    background.setPosition(2, 0, -5)
    sceneManager.register(background)
    let sceneGLTF = new ACTOR.MeshActor('Scene', assetMap.get('../assets/scene.glb'))
    sceneGLTF.setPosition(-39, -10.5, 60.4)
    sceneManager.register(sceneGLTF) 
    let roofGLTF = new ACTOR.MeshActor('Roof', assetMap.get('../assets/eq_animation.glb'))
    roofGLTF.applyColor(MISC.MISC.hexToColor(colors[0]))
    roofGLTF.setPosition(2, -2, -3)
    sceneManager.register(roofGLTF) 
    slider.setCallback((deltaValue, value, typeName)=>{
        if (typeName == 'slider-light')
        {    
            navBarLightItem.setCustomValue('sliderValue', value)
            directLight.orbit(deltaValue)
        }
        else if (typeName == 'slider-roof')
        {
            navBarRoofItem.setCustomValue('sliderValue', value)
            roofGLTF.updateAnimationFrame(-(deltaValue/180))
        }
    })
    let HOTSPOT = importMap.get('HOTSPOT')
    let MATHS = importMap.get('MATHS')
    let VIDEO = importMap.get('VIDEO')
    let videoPlayer = new VIDEO.VideoPlayer(document.getElementById('video-screen'), document.querySelector('video'), document.getElementById('cross-icon'))
    videoPlayer.setOnCloseEvent((e)=>videoPlayer.show(false)) 
    videoPlayer.show(false)
    let hotSpot1 = new HOTSPOT.Hotspot(MATHS.MATHS.addVectors(roofGLTF.getPosition(), new THREE.Vector3(-3.55, 2.4, 0.01)))
    hotSpot1.setRenderCondition(()=>{ return !videoPlayer.isShowing() })
    hotSpot1.setOnClick((e)=>videoPlayer.show(true))
    hotSpot1.setOnDblClick(()=>sceneManager.broadcastTo(roofGLTF.name, cameraManager.name, hotSpot1.worldPosition))
    let hotSpot2 = new HOTSPOT.Hotspot(MATHS.MATHS.addVectors(roofGLTF.getPosition(), new THREE.Vector3(-0.85, 2.4, 0.01)))
    hotSpot2.setRenderCondition(()=>{ return !videoPlayer.isShowing() })
    hotSpot2.setOnClick((e)=>videoPlayer.show(true))
    hotSpot2.setOnDblClick(()=>sceneManager.broadcastTo(roofGLTF.name, cameraManager.name, hotSpot2.worldPosition))
    let hotSpot3 = new HOTSPOT.Hotspot(MATHS.MATHS.addVectors(roofGLTF.getPosition(), new THREE.Vector3(-3.25, 2.4, -3.2)))
    hotSpot3.setRenderCondition(()=>{ return !videoPlayer.isShowing() })
    hotSpot3.setOnClick((e)=>videoPlayer.show(true))
    hotSpot3.setOnDblClick(()=>sceneManager.broadcastTo(roofGLTF.name, cameraManager.name, hotSpot3.worldPosition))
    roofGLTF.addHotSpots(hotSpot1)
    roofGLTF.addHotSpots(hotSpot2)
    roofGLTF.addHotSpots(hotSpot3)
    colorMenu.populateItems(document.getElementById('color-menu'), (color)=>{
        roofGLTF.applyColor(MISC.MISC.hexToColor(color))
        arViewer.setColor(color)
    })
    colorMenu.show(false)
    loadingScreen.show(false)
}